//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOturum
{
    using System;
    using System.Collections.Generic;
    
    public partial class masalar
    {
        public int id { get; set; }
        public System.DateTime bitirme_tarihi { get; set; }
        public string kat { get; set; }
        public string masa_sayisi { get; set; }
        public int user_id { get; set; }
    
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
