//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOturum
{
    using System;
    using System.Collections.Generic;
    
    public partial class yardim
    {
        public int id { get; set; }
        public string soru_icerik { get; set; }
        public string soru_turu { get; set; }
        public string soruBaslik { get; set; }
        public System.DateTime tarih { get; set; }
        public int soran_id { get; set; }
    
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
